apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sbi-network
  namespace: open5gs
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "bridge",
      "bridge": "br-int",
      "promiscMode": true,
      "ipam": {
        "type": "static"
      }
    }'
