apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: open5gs
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:4.4.10
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
      volumes:
      - name: mongodb-data
        hostPath:
          path: /var/lib/open5gs/mongodb
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: open5gs
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
