apiVersion: v1
kind: ConfigMap
metadata:
  name: nrf-config
  namespace: open5gs
data:
  nrf.yaml: |
    logger:
      file:
        path: /opt/open5gs/var/log/open5gs/nrf.log

    global:

    nrf:
      serving:
      - plmn_id:
          mcc: 999
          mnc: 70

      sbi:
        server:
        - dev: net1
          port: 7777

    metrics:
      server:
      - address: net1
        port: 9090

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nrf
  namespace: open5gs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nrf
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [
            { "name": "sbi-network", "ips": ["10.10.10.10/24"] }
          ]
      labels:
        app: nrf
    spec:
      containers:
      - name: nrf
        image: gradiant/open5gs:2.7.6
        command: ["/opt/open5gs/bin/open5gs-nrfd"]
        args: ["-c", "/opt/open5gs/etc/open5gs/nrf.yaml"]
        env:
        - name: DB_URI
          value: "mongodb://mongodb:27017/open5gs"
        ports:
        - containerPort: 7777
          name: sbi
        - containerPort: 9090
          name: metrics
        volumeMounts:
        - name: nrf-config
          mountPath: /opt/open5gs/etc/open5gs/nrf.yaml
          subPath: nrf.yaml
      volumes:
      - name: nrf-config
        configMap:
          name: nrf-config

---
apiVersion: v1
kind: Service
metadata:
  name: nrf
  namespace: open5gs
spec:
  clusterIP: None
  ports:
  - name: sbi
    protocol: TCP
    port: 7777
    targetPort: 7777
  - name: metrics
    protocol: TCP
    port: 9090
    targetPort: 9090

---
apiVersion: v1
kind: Endpoints
metadata:
  name: nrf
  namespace: open5gs
subsets:
  - addresses:
      - ip: 10.10.10.10
    ports:
      - name: sbi
        port: 7777
        protocol: TCP
      - name: metrics
        port: 9090
        protocol: TCP

