apiVersion: apps/v1
kind: Deployment
metadata:
  name: udm
  namespace: open5gs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udm
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
          { "name": "sbi-network", "ips": ["10.10.10.14/24"] }
        ]'
      labels:
        app: udm
    spec:
      containers:
      - name: udm
        image: gradiant/open5gs:2.7.6
        command: ["/bin/sh", "-c"]
        args:
          - |
            sed -i 's/dev: eth0/dev: net1/g' /opt/open5gs/etc/open5gs/udm.yaml
            sed -i 's/addr: 127.0.0.3/addr: 0.0.0.0/g' /opt/open5gs/etc/open5gs/udm.yaml
              #sed -i 's|http://nrf:7777|http://10.10.10.10:7777|g' /opt/open5gs/etc/open5gs/udm.yaml
              #sed -i 's|http://scp:7777|http://10.10.10.11:7777|g' /opt/open5gs/etc/open5gs/udm.yaml
            /opt/open5gs/bin/open5gs-udmd -c /opt/open5gs/etc/open5gs/udm.yaml
        env:
        - name: DB_URI
          value: "mongodb://mongodb:27017/open5gs"
        ports:
        - containerPort: 7777
---
apiVersion: v1
kind: Service
metadata:
  name: udm
  namespace: open5gs
spec:
  clusterIP: None
  ports:
    - name: sbi
      protocol: TCP
      port: 7777
      targetPort: 7777
    - name: metrics
      protocol: TCP
      port: 9090
      targetPort: 9090

---
apiVersion: v1
kind: Endpoints
metadata:
  name: udm
  namespace: open5gs
subsets:
  - addresses:
      - ip: 10.10.10.14
    ports:
      - name: sbi
        port: 7777
        protocol: TCP
      - name: metrics
        port: 9090
        protocol: TCP
