apiVersion: apps/v1
kind: Deployment
metadata:
  name: upf
  namespace: open5gs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upf
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [
            { "name": "sbi-network", "ips": ["10.10.10.21/24"] }
          ]
      labels:
        app: upf
    spec:
      containers:
      - name: upf
        image: gradiant/open5gs:2.7.6
        securityContext:
          privileged: true
          allowPrivilegeEscalation: true
          runAsUser: 0
          capabilities:
            add: ["NET_ADMIN", "NET_RAW", "SYS_ADMIN"]
          seccompProfile:
            type: Unconfined
        volumeMounts:
          - name: dev-net-tun
            mountPath: /dev/net/tun
        command: ["/bin/sh", "-c"]
        args:
          - |
            ls -l /dev/net/tun

            ip tuntap add name ogstun mode tun || true
            ip addr add 10.45.0.1/16 dev ogstun || true
            ip link set ogstun up || true

            iptables -t nat -A POSTROUTING -s 10.45.0.0/16 ! -o ogstun -j MASQUERADE || true

            sed -i 's/dev: eth0/dev: net1/g' /opt/open5gs/etc/open5gs/upf.yaml
            sed -i 's/addr: 127.0.0.7/addr: 0.0.0.0/g' /opt/open5gs/etc/open5gs/upf.yaml

            /opt/open5gs/bin/open5gs-upfd -c /opt/open5gs/etc/open5gs/upf.yaml
        ports:
        - containerPort: 8805
          protocol: UDP
        - containerPort: 2152
          protocol: UDP
      volumes:
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice
---
apiVersion: v1
kind: Service
metadata:
  name: upf
  namespace: open5gs
spec:
  clusterIP: None
  ports:
    - name: n4
      protocol: UDP
      port: 8805
      targetPort: 8805
    - name: n3
      protocol: UDP
      port: 2152
      targetPort: 2152
    - name: metrics
      protocol: TCP
      port: 9090
      targetPort: 9090
---
apiVersion: v1
kind: Endpoints
metadata:
  name: upf
  namespace: open5gs
subsets:
  - addresses:
      - ip: 10.10.10.21
    ports:
      - name: n4
        port: 8805
        protocol: UDP
      - name: n3
        port: 2152
        protocol: UDP
      - name: metrics
        port: 9090
        protocol: TCP

