apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui
  namespace: open5gs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webui
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
          { "name": "sbi-network", "ips": ["10.10.10.19/24"] }
        ]'
      labels:
        app: webui
    spec:
      containers:
      - name: webui
        image: gradiant/open5gs-webui:2.7.6
        env:
        - name: DB_URI
          value: "mongodb://mongodb:27017/open5gs"
        - name: MONGODB_URL
          value: "mongodb://mongodb:27017/open5gs"
        ports:
        - containerPort: 9999
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: webui
  namespace: open5gs
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 9999
      targetPort: 9999
      nodePort: 30000
---
apiVersion: v1
kind: Endpoints
metadata:
  name: webui
  namespace: open5gs
subsets:
  - addresses:
      - ip: 10.10.10.19
    ports:
      - port: 9999
